export const initialFieldValues = {
    name: '',
    id: '',
    date1value: Date.now(),
    date2value: Date.now(),
    date3value: Date.now(),
    string1value: '',
    string2value: '',
    string3value: '',
    int1value: '',
    int2value: '',
    int3value: '',
    text1value: '',
    text2value: '',
    text3value: '',
    check1value: false,
    check2value: false,
    check3value: false,
  };