export const initialFieldValues = {
  name: '',
  topic: '',
  description: '',
  integer1name: '',
  integer2name: '',
  integer3name: '',
  string1name: '',
  string2name: '',
  string3name: '',
  data1name: '',
  data2name: '',
  data3name: '',
  text1name: '',
  text2name: '',
  text3name: '',
  checkbox1name: '',
  checkbox2name: '',
  checkbox3name: '',
};

export const showOptionalFields = {
  integer1: false,
  integer2: false,
  integer3: false,
  string1: false,
  string2: false,
  string3: false,
  data1: false,
  data2: false,
  data3: false,
  text1: false,
  text2: false,
  text3: false,
  checkbox1: false,
  checkbox2: false,
  checkbox3: false,
};
